/*
package com.nanyang.app.main.home.sport.main;
SocOddsId
        PreSocOddsId
        SocOddsId_FH
        Live
        IsLastCall
        MatchDate
         Status
        CurMinute
        IsInetBet
        IsHomeGive
        RTSMatchId
        HomeId
        AwayId
         Home
        Away
        HomeRank
        AwayRank
        RunHomeScore
        RunAwayScore
        RCHome
        RCAway
         GamesSum
        Hdp
        OU
        HOdds
        AOdds
        OOdds
        UOdds
        OddOdds
        EvenOdds
        X12_1Odds
        X12_XOdds
        X12_2Odds
        HdpOdds
        OUOdds
        OEOdds
        HasPar
         IsInetBet_FH
        IsHomeGive_FH
        Hdp_FH
        OU_FH
        HOdds_FH
        AOdds_FH
        OOdds_FH
        UOdds_FH
        OddOdds_FH
        EvenOdds_FH
        X12_1Odds_FH
        X12_XOdds_FH
        X12_2Odds_FH
        HdpOdds_FH
        OUOdds_FH
        OEOdds_FH
        StatsId
        MExtraTime
         WorkingDate
        HasPar_FH
        TvPathIBC

      [716993
       0
        717023
         '1 - 0'
          0
           '25/03 10:30AM'
            1
             17
              1
               1
                0
                 84401
                  84264
                   'AS Los Angeles'
                    'Oxnard Guerreros FC'
                     ''
                      ''
                       1
                        0
                         0
                          0
                           13
                            0.75
                             3.5
                              8.8
                               9.3
                                -9.9
                                 7.8
                                  9.3
                                   9.5
                                    1.21
                                     5
                                      10
                                       -9.3
                                        -7.8
                                         -9.3
                                          1
                                           1
                                            1
                                             0.25
                                              1.75
                                               8.6
                                                9.5
                                                 9
                                                  8.9
                                                   0
                                                    0
                                                     1.14
                                                      4.45
                                                       55
                                                        -9.5
                                                         -8.9
                                                          0
                                                           0
                                                            '0'
                                                             '2019/3/24 0:00:00'
                                                              1
                                                               ''

*/
